version: '3'
services:
    laravel:
        build:
            context: ./docker
            dockerfile: Dockerfile
        ports:
            - '8000:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        ports:
            - '3336:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
