#!/usr/bin/env bash

composer install

cp .env.example .env
php artisan key:generate
php artisan migrate --path=app/Infrastructure/Migrations

/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
